export const lightTheme = {
    body: '#F0F3F5',
    text: '#363537',
    sidebar: "#fff",
    sidebar_text_color: "#011B57BF",
    sidebar_icon_color:"#011B57BF",
    home_text_h1_color:"#01133C",
    home_text_p_color:"#C3CDD6",
    shipment_header_h1_color:"#01133C",
    shipment_header_p_color:"#C3CDD6",
    shipment_btns_background:"#fff",
    shipment_button_color:"#00173788",
    charts_section_background:"#fff",
    feature_card_container_background:"#fff",
    feature_card_text_h5_color:"#C3CDD6",
    feature_card_text_h1_color:"#01133C",
    feature_card_text_p_color:"#C3CDD6",
    chart_header_p_color:"#01133C89",
    chart_header_h1_color:"#001737",
    notif_icon_color:"#01133C",
    vehicle_text_h1_color: "#01133C",
    vehicle_text_p_color: "#C3CDD6",
    vehicle_container_background_color:"#F6F8FB",
    vehicle_link_h4_color:"#9BA3A0",
    vehicle_search_btn_color:"#0B0314C6",
    vehicle_card_container_background_color:"#FFF",
    vehicle_card_text_h1_color:"#0A0A0A",
    vehicle_truck_icon_color:"#000819DB",
    vehicle_icon_color:"#000000",
    vehicle_modal_container_background_color:"#FFF",
    vehicle_modal_close_icon_background_color:"#FFF",
    vehicle_modal_close_icon_color:"#000",
    vehicle_modal_close_icon_border_color:"#200E32",
    top_vehicle_modal_h1_color:"#01133C",
    top_vehicle_modal_p_color:"#01133C",
    bottom_modal_h1_color:"#0A0A0A",
    bottom_modal_p_color:"#7A8395",
    bottom_modal_icon_color:"#000",
    middle_modal_h1_color:"#0A0A0A",
    middle_modal_p_color:"#7A8395",
    middle_modal_icon_color:"#011B57",
    

}
export const darkTheme = {
    body: '#010A1D',
    text: '#FAFAFA',
    sidebar:"#04122E",
    sidebar_text_color: "#D4DFF7BF",
    sidebar_icon_color:"#D4DFF7BF",
    home_text_h1_color:"#FFFFFF",
    home_text_p_color:"#FAFAFA93",
    shipment_header_h1_color:"#FFFFFF",
    shipment_header_p_color:"#FAFAFA93",
    shipment_btns_background:"#031333",
    shipment_button_color:"#FFFFFF88",
    charts_section_background:"#04122E",
    feature_card_container_background:"#04122E",
    feature_card_text_h5_color:"#FFFFFF89",
    feature_card_text_h1_color:"#FFF",
    feature_card_text_p_color:"#FFF",
    chart_header_p_color:"#FFFFFF89",
    chart_header_h1_color:"#FFF",
    notif_icon_color:"#FFF",
    vehicle_text_h1_color: "#FFF",
    vehicle_text_p_color: "#FAFAFA93",
    vehicle_container_background_color:"#060D1C",
    vehicle_link_h4_color:"#FFFFFFA2",
    vehicle_search_btn_color:"#FFFFFFC6",
    vehicle_card_container_background_color:"#081124",
    vehicle_card_text_h1_color:"#FFFFFF",
    vehicle_truck_icon_color:"#FFFFFFDB",
    vehicle_icon_color:"#FFF",
    vehicle_modal_container_background_color:"#020A1A",
    vehicle_modal_close_icon_background_color:"#020A1A",
    vehicle_modal_close_icon_color:"#FFF",
    vehicle_modal_close_icon_border_color:"#FFF",
    top_vehicle_modal_h1_color:"#FFFFFF",
    top_vehicle_modal_p_color:"#FFFFFF93",
    bottom_modal_h1_color:"#FFF",
    bottom_modal_p_color:"#7A8395",
    bottom_modal_icon_color:"#FFFFFFBF",
    middle_modal_h1_color:"#FFFFFF",
    middle_modal_p_color:"#7A8395",
    middle_modal_icon_color:"#FFF",



}